#!/usr/bin/env python3
"""Refresh the global and project rules for THIS machine.

Three jobs, each a separate flag so the risky one is always a human's:

    refresh_rules.py --machine              # report the detected machine facts only
    refresh_rules.py --global               # render global/CLAUDE.md + the machine block
    refresh_rules.py --statements [CAT...]  # render adoptable rule statements

Reports on stdout. Writes nothing unless --write is passed, and --write refuses a
read-only target rather than half-applying.

The REFUSAL that matters lives in `statements()`: a rule with no machine-extractable
statement stops the run and is named. It is never emitted as a bare link -- a silent
fallback to links is the defect the whole thing exists to fix.
See rules/how-we-work/a-rule-states-itself-in-one-line.md.
"""
import argparse
import locale
import os
import platform
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "lib"))
import rulestatement  # noqa: E402  -- the ONE parser; never re-implement it

REPO = Path(__file__).resolve().parents[2]
RULES = REPO / "rules"
GLOBAL_SRC = REPO / "global" / "CLAUDE.md"

# how-we-work is never optional; the cap binds the domain categories
ALWAYS = "how-we-work"
MAX_RULES = rulestatement.RULE_CEILING


# ---------------------------------------------------------------- machine facts
def detect_machine():
    """Every value derived from state. Nothing here is typed by anyone."""
    facts = {}
    facts["os"] = platform.system()
    facts["release"] = platform.release()
    facts["arch"] = platform.machine()

    # container or host, by evidence rather than by a name
    signals = []
    if Path("/.dockerenv").exists():
        signals.append("/.dockerenv")
    try:
        cg = Path("/proc/1/cgroup").read_text(encoding="utf-8", errors="replace")
        if "docker" in cg or "containerd" in cg:
            signals.append("/proc/1/cgroup")
    except OSError:
        pass
    facts["kind"] = "container" if signals else "host"
    facts["kind_evidence"] = ", ".join(signals) if signals else "no container signal"

    # purpose comes from the repo's own committed declaration, never guessed
    facts["purpose"] = "undeclared"
    decl = REPO / ".claude-session"
    if decl.exists():
        kv = {}
        for line in decl.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                kv[k.strip()] = v.strip()
        bits = [kv[k] for k in ("target", "container") if kv.get(k)]
        if bits:
            facts["purpose"] = " / ".join(bits)

    # encoding -- the cp1252 / cp874 trap
    facts["filesystem_encoding"] = sys.getfilesystemencoding()
    try:
        facts["preferred_encoding"] = locale.getpreferredencoding(False)
    except Exception:
        facts["preferred_encoding"] = "unknown"
    facts["utf8_mode"] = os.environ.get("PYTHONUTF8", "unset")
    return facts


def machine_block(facts):
    out = ["## This machine", ""]
    out.append("<!-- generated by skills/refresh-rules -- every value read from state. -->")
    out.append("<!-- Edit global/CLAUDE.md in the shared repo, never this copy. -->")
    out.append("")
    out.append("| fact | value | read from |")
    out.append("|---|---|---|")
    out.append("| os | `%s %s` (%s) | `platform` |" % (facts["os"], facts["release"], facts["arch"]))
    out.append("| kind | **%s** | %s |" % (facts["kind"], facts["kind_evidence"]))
    out.append("| purpose | %s | `.claude-session` |" % facts["purpose"])
    out.append("| filesystem encoding | `%s` | `sys` |" % facts["filesystem_encoding"])
    out.append("| preferred encoding | `%s` | `locale` |" % facts["preferred_encoding"])
    out.append("")
    if facts["preferred_encoding"].lower().replace("-", "") not in ("utf8", "utf8mb4"):
        out.append("⚠️ **This machine's preferred encoding is not UTF-8.** Pass `encoding=\"utf-8\"` "
                   "explicitly on every `open()`; the locale codec silently corrupts text that a "
                   "UTF-8 machine reads back. See `rules/data-engineering/text-encoding.md`.")
        out.append("")
    if facts["kind"] == "container":
        out.append("⚠️ **Container.** `~/.claude/CLAUDE.md` may be a read-only mount here; check "
                   "before planning an edit to it. A credential this session needs is MOUNTED, so "
                   "look in `~/.config` before reporting an authentication blocker.")
        out.append("")
    return "\n".join(out)


# ------------------------------------------------------------ rule statements
def statement_of(path):
    return rulestatement.extract_path(path)


def title_of(path):
    return rulestatement.title(path.read_text(encoding="utf-8"), path.stem)


def statements(categories, pin):
    """Render adoptable statements. REFUSES on any rule with no statement."""
    cats = [ALWAYS] + [c for c in categories if c != ALWAYS]
    picked, missing = [], []
    for cat in cats:
        d = RULES / cat
        if not d.is_dir():
            print("no such category: %s" % cat, file=sys.stderr)
            return None, 2
        for f in sorted(d.glob("*.md")):
            st = statement_of(f)
            if st is None:
                missing.append(f.relative_to(REPO))
            else:
                picked.append((cat, f, st))

    if missing:
        print("REFUSED -- %d rule(s) have no machine-extractable statement:" % len(missing),
              file=sys.stderr)
        for m in missing:
            print("  %s" % m, file=sys.stderr)
        print("", file=sys.stderr)
        print("A rule with no statement would be adopted as a bare URL, which is the defect this",
              file=sys.stderr)
        print("tool exists to fix. Fix the rule file; the fallback is deliberately absent.",
              file=sys.stderr)
        print("See rules/how-we-work/a-rule-states-itself-in-one-line.md", file=sys.stderr)
        return None, 1

    counts = {}
    for cat, _f, _st in picked:
        counts[cat] = counts.get(cat, 0) + 1
    msg = rulestatement.over_ceiling(counts)
    if msg:
        print(msg, file=sys.stderr)
        return None, 1

    out = ["## Rules in force", ""]
    out.append("<!-- adopted by skills/refresh-rules at pin %s -->" % pin)
    out.append("")
    cur = None
    for cat, f, st in picked:
        if cat != cur:
            out.append("### %s" % cat)
            out.append("")
            cur = cat
        rel = f.relative_to(REPO).as_posix()
        url = ("https://github.com/surasakcho/agentic-ai-rules-and-skills/blob/%s/%s" % (pin, rel))
        out.append("- **%s** — %s" % (title_of(f), st))
        out.append("  [full rule](%s)" % url)
        out.append("")
    return "\n".join(out), 0


# ------------------------------------------------------------------------ main
def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--machine", action="store_true", help="report detected machine facts")
    ap.add_argument("--global", dest="glob", action="store_true",
                    help="render global/CLAUDE.md verbatim + the machine block")
    ap.add_argument("--statements", nargs="*", metavar="CAT",
                    help="render adoptable rule statements for these domain categories")
    ap.add_argument("--pin", default="HEAD", help="sha to build rule links against")
    ap.add_argument("--write", metavar="PATH", help="write the rendered output to PATH")
    a = ap.parse_args()

    facts = detect_machine()
    if a.machine:
        for k, v in facts.items():
            print("%-20s %s" % (k, v))
        return 0

    if a.glob:
        if not GLOBAL_SRC.exists():
            print("missing source: %s" % GLOBAL_SRC, file=sys.stderr)
            return 2
        rendered = GLOBAL_SRC.read_text(encoding="utf-8").rstrip() + "\n\n---\n\n" + machine_block(facts)
    elif a.statements is not None:
        rendered, code = statements(a.statements, a.pin)
        if rendered is None:
            return code
    else:
        ap.print_help()
        return 0

    if not a.write:
        print(rendered)
        return 0

    target = Path(a.write).expanduser()
    real = target.resolve() if target.exists() else target
    if target.exists() and not os.access(real, os.W_OK):
        print("REFUSED -- %s is not writable (read-only mount?)." % real, file=sys.stderr)
        print("Nothing was written. Emit it and hand it to whoever can apply it.", file=sys.stderr)
        return 1
    target.write_text(rendered + "\n", encoding="utf-8")
    print("wrote %d lines to %s" % (rendered.count("\n") + 1, target))
    return 0


if __name__ == "__main__":
    sys.exit(main())
